### ISSUE TITLE
[BUG] Cannot connect to Hypixel

### ISSUE THREAD

**Issue by lightumcc** [Ghost-chu/CustomClientDNS#3]
```
[14:08:23] [Server Pinger #3/INFO]: Successfully got DNS record of type 'A' for hostname 'mc.hypixel.net': 'mc.hypixel.net.	10 IN	A	209.222.114.80'
```
<img width="1836" alt="image" src="https://github.com/Ghost-chu/CustomClientDNS/assets/60721270/adf66aa6-c52e-42a3-843f-a970a6d04862">

This issue may appears in other `Connection Domain Restriction` server

**Comment by Ghost-chu** [comment]
fixed in 1.1 on Modrinth.

**Comment by lightumcc** [comment]
Sorry, but your latest version cannot run on 1.20.4
> Modrinth said this mod can run on 1.20.3-1.20.4
```
有不兼容的模组！ (Incompatible mods found!)
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
确定了一种可能的解决方法，这样做可能会解决你的问题：
	 - 将 模组 'CustomClientDNS' (customclientdns) 1.1 替换为与这一模组兼容的 任意版本：
		 - minecraft 1.20.4
更多信息：
	 - 模组 'CustomClientDNS' (customclientdns) 1.1 需要 'Minecraft' (minecraft) 的 1.20.3 版本，但已经安装了的版本 1.20.4 不对！
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
(Sorry for providing only Chinese version)

**Comment by Ghost-chu** [comment]
已重新发布正确的构建 （1.20.4）
